{% set name = "xcube-4d-viewer" %}
{% set version = "1.0.16" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/xcube_4d_viewer-{{ version }}.tar.gz
  sha256: 2960245137f888e6916ca09187e606ec5363c2670f1a83a8cc76ea4cd86562c4

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 1

requirements:
  host:
    - python {{ python_min }}
    - pip
  run:
    - python >={{ python_min }}
    - xcube

test:
  imports:
    - xcube_4d_viewer
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://pypi.org/project/xcube-4d-viewer/
  summary: API extension to the xcube server allowing cubes to be visualised in the Earthwave 4D viewer.
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - juliabizon
    - earthwave-admin
